
[package]
name = "futures_cpp"
version = "0.1.0"
authors = ["Yuheng Chen <yuhengchen@sensetime.com>"]

[exports]
includes = ["include"]

[dependencies.gtest]
branch = "cppbuild"
url = "git@gitlab.bj.sensetime.com:core/googletest.git"

[dependencies.BoostParts]
branch = "master"
url = "git@gitlab.bj.sensetime.com:core/BoostParts.git"

[dependencies.libev]
branch = "master"
url = "git@gitlab.bj.sensetime.com:core/libev.git"

[dependencies.boringssl]
branch = "cppbuild"
url = "git@gitlab.bj.sensetime.com:core/boringssl.git"
optional = true

[dependencies.zlib]
branch = "master"
url = "git@gitlab.bj.sensetime.com:core/zlib.git"
optional = true

[option.ssl]
default = true
depend_on = ["boringssl"]

[option.zlib]
default = true
depend_on = ["zlib"]
